name: fruits_hub_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.6
  dartz: ^0.10.1
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  skeletonizer: ^1.4.3
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
