// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAgKz3YWE0daYCI-v2xrycYTGRCtxnejI',
    appId: '1:331453867837:web:ce6d6b49acf218a5c9c754',
    messagingSenderId: '331453867837',
    projectId: 'fruits-hub-17ccd',
    authDomain: 'fruits-hub-17ccd.firebaseapp.com',
    storageBucket: 'fruits-hub-17ccd.firebasestorage.app',
    measurementId: 'G-WKTN49RRX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWtJcnq8RwHEGz_K0_-VF2lyYfclJ0a9o',
    appId: '1:331453867837:android:478b788a0e9a8768c9c754',
    messagingSenderId: '331453867837',
    projectId: 'fruits-hub-17ccd',
    storageBucket: 'fruits-hub-17ccd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEipHpMgyB3UdHR83etek_glI6O7DbTUE',
    appId: '1:331453867837:ios:19ae3b7610292e9fc9c754',
    messagingSenderId: '331453867837',
    projectId: 'fruits-hub-17ccd',
    storageBucket: 'fruits-hub-17ccd.firebasestorage.app',
    androidClientId: '331453867837-59mm26kvrckf74e7g5hgopvarrql1vnr.apps.googleusercontent.com',
    iosClientId: '331453867837-jo2pou0oksn8vcmp3ckbnq3ko7nm7b3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEipHpMgyB3UdHR83etek_glI6O7DbTUE',
    appId: '1:331453867837:ios:19ae3b7610292e9fc9c754',
    messagingSenderId: '331453867837',
    projectId: 'fruits-hub-17ccd',
    storageBucket: 'fruits-hub-17ccd.firebasestorage.app',
    androidClientId: '331453867837-59mm26kvrckf74e7g5hgopvarrql1vnr.apps.googleusercontent.com',
    iosClientId: '331453867837-jo2pou0oksn8vcmp3ckbnq3ko7nm7b3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAgKz3YWE0daYCI-v2xrycYTGRCtxnejI',
    appId: '1:331453867837:web:79f645fd2e9c389bc9c754',
    messagingSenderId: '331453867837',
    projectId: 'fruits-hub-17ccd',
    authDomain: 'fruits-hub-17ccd.firebaseapp.com',
    storageBucket: 'fruits-hub-17ccd.firebasestorage.app',
    measurementId: 'G-9BTVWD3PF9',
  );
}
